### ISSUE TITLE
Missing license files

### ISSUE THREAD

**Issue by dariagrudzien** [lzrski/node-damerau-levenshtein#10]
@lzrski Hi Tadeusz, thank you for this package. Would you mind adding the license file to the repo & the npm package? Without it we're not really able to use it, because it makes the npm package a distribution of proprietary code.

Many thanks.

**Comment by tad-lispy** [comment]
Hello, @dariagrudzien. Thanks for bringing this to my attention. I've added BSD-2 clause license. May I ask where are you using this package?

**Comment by dariagrudzien** [comment]
@lzrski I'm not, but [eslint-plugin-jsx-a11y@6.1.2](https://www.npmjs.com/package/eslint-plugin-jsx-a11y) is :) thanks!
