### ISSUE TITLE
Transposition doesn`t make right.

### ISSUE THREAD

**Issue by g-adolph** [lzrski/node-damerau-levenshtein#2]
I think you forgotten to add "__" on "this[i-2]" because it's need to be the original "this" term and not exist the this is the function scope not any variable.

for me that seens to like `matrix[i][j] = (i > 1 && j > 1 && this_i === that[j-2] &&` **__this[i-2]**`=== that_j && (t = matrix[i-2][j-2]+cost) < min) ? t : min; // Transposition.`

**Comment by tad-lispy** [comment]
Hello. Thanks for reporting. 

What's the impact? Could you please demonstrate a case where it throws / produces wrong values?

I think this project would use some tests. Maybe it's a good opportunity to introduce them?

**Comment by tad-lispy** [comment]
Your PR is now [released on NPM as v. 1.0.1](https://www.npmjs.com/package/damerau-levenshtein). Thank you very much :)
