### ISSUE TITLE
Math.min() is faster now

### ISSUE THREAD

**Issue by LJNeon** [lzrski/node-damerau-levenshtein#9]
https://github.com/lzrski/node-damerau-levenshtein/blob/master/index.js#L44 claims that it's faster to use `if` statements than `Math.min()`, however on the latest version of node.js `Math.min()` is ~3x faster. Note that you can use more than 2 arguments for `Math.min()`, using it repeatedly with only two arguments is indeed slower.

**Comment by tad-lispy** [comment]
Thanks! Would you care to open a PR?

**Comment by LJNeon** [comment]
Sorry but I got a backlog of things to code, I might be able to get to this eventually if I remember but it won't be anytime soon.

**Comment by tad-lispy** [comment]
Ok, sure. No pressure.

I guess it would be nice to have some sort of benchmark.

**Comment by LJNeon** [comment]
In the newer updates of node.js both `Math.min()` and the current method have become significantly faster, and they are now both the same speed.
